services:

  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./prepa1
    container_name: spring-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/prepa1db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    build: ./angular-prepa
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:
