spring.application.name=prepa1

# ========================
# PostgreSQL
# ========================



#spring.datasource.url=exists in application-docker.properties and application-local.properties
# the choice is based on the value of :
#here : spring.profiles.active=local
#and 
#docker-compose.yml : - SPRING_PROFILES_ACTIVE=docker

spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Affichage SQL (optionnel)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=local
